version: '3.3'
services:
  user-service:
    container_name: nest-user-service
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://mongo:27017/users
      - REDIS_PORT=6379
      - REDIS_HOST=redis

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
